name: Python application

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 0180
          POSTGRES_DB: FitnessAppDB
        ports:
          - 5432:5432
        # Ставим паузу для того, чтобы контейнер успел запуститься
        options: --health-cmd="pg_isready -U user" --health-timeout=30s --health-retries=5

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python 3.12.1
        uses: actions/setup-python@v3
        with:
          python-version: "3.12.1"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Set environment variables
        run: |
          echo "DATABASE_URL=postgresql://postgres:0180@localhost:5432/FitnessAppDB" >> $GITHUB_ENV

      - name: Lint with flake8
        run: |
          # stop the build if there are Python syntax errors or undefined names
          flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
          # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
          flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics

      - name: Test with pytest
        run: |
          pytest
